Repository morpho-org/morpho-optimizers, pull requests merged in 2024-03, with the labels that each got.

#1671 fix(ci): remove autodoc CI
  .github/workflows/ci-docs-autogen.yml
  README.md
Labels: ⚙️ ci

#1672 auto trigger ci periodically
  .github/workflows/ci-foundry-aave-v2-upgrade.yml
  .github/workflows/ci-foundry-compound-upgrade.yml
Labels: ⚙️ ci

#1676 Skip lens rate tests when over utilized
  test/prod/aave-v2/TestLifecycle.t.sol
  test/prod/compound/TestLifecycle.t.sol
  test/prod/compound/TestUpgradeLens.t.sol
  test/prod/compound/setup/TestSetup.sol
Labels: 🧪 testing

#1675 Skip upgrade tests in revert conditions
  test/prod/aave-v2/TestLifecycle.t.sol
  test/prod/aave-v2/TestUpgradeLens.t.sol
  test/prod/compound/TestLifecycle.t.sol
  test/prod/compound/TestUpgradeLens.t.sol
  test/prod/compound/setup/TestSetup.sol
Labels: 🧪 testing

#1656 Certora formally verified rewards checker
  .github/workflows/ci-certora.yml
  .gitignore
  certora/README.md
  certora/checker/Checker.sol
  certora/checker/create_certificate.py
  certora/confs/MerkleTrees.conf
  certora/confs/RewardsDistributor.conf
  certora/helpers/MerkleTreeLib.sol
  certora/helpers/MerkleTrees.sol
  certora/helpers/MorphoToken.sol
  certora/specs/MerkleTrees.spec
  certora/specs/RewardsDistributor.spec
  foundry.toml
Labels: ⚙️ ci, 🧮 certora
